Repository victoriadrake/hugo-theme-introduction, pull requests merged in 2019-08, with the labels that each got.

#160 Add test for hugo 0.56
  .travis.yml
  exampleSite/resources/_gen/assets/sass/sass/style.sass_ed49e085717c1c90f2122c5f5731b8cc.content
  exampleSite/resources/_gen/assets/sass/sass/style.sass_ed49e085717c1c90f2122c5f5731b8cc.json
Labels: enhancement

#161 Changed npm cmd for prereq
  README.md
Labels: in review

#165 Added Chinese Translations
  i18n/zh-CN.toml
  i18n/zh-TW.toml
Labels: enhancement

#166 More French word for bug
  i18n/fr.toml
Labels: bug, in review

#170 Removed trailing spaces and missing newline at EOF
  .gitignore
  archetypes/default.md
  archetypes/projects.md
  assets/vendor/fontawesome-free/LICENSE.txt
  exampleSite/content/en/blog/no-date.md
  exampleSite/content/en/projects/design/index.md
  layouts/index.html
  netlify.toml
  scripts/build_docs.sh
Labels: in review

#177 Add `timeRefresh` for periodic localtime update and allow for multilingual time format
  assets/js/initMoment.js
  layouts/index.html
Labels: enhancement, in review
