Repository victoriadrake/hugo-theme-introduction, pull requests merged in 2019-04, with the labels that each got.

#146 Replace deprecated RSSLink
  docs/de/index.html
  docs/es/index.html
  docs/index.html
  exampleSite/resources/_gen/assets/sass/sass/style.sass_7642ba43b3212fd7d7ba324df3b88b0c.content
  exampleSite/resources/_gen/assets/sass/sass/style.sass_7642ba43b3212fd7d7ba324df3b88b0c.json
  layouts/partials/head/metadata.html
Labels: enhancement

#143 Order sections on homepage by weigth
  README.md
  exampleSite/content/de/blog/_index.md
  exampleSite/content/de/home/about.md
  exampleSite/content/de/home/lorem.md
  exampleSite/content/de/projects/_index.md
  exampleSite/content/en/blog/_index.md
  exampleSite/content/en/home/about.md
  exampleSite/content/en/home/lorem.md
  exampleSite/content/en/projects/_index.md
  exampleSite/content/es/blog/_index.md
  exampleSite/content/es/home/about.md
  exampleSite/content/es/home/lorem.md
  exampleSite/content/es/projects/_index.md
  layouts/index.html
Labels: in review

#148 Fix NPE if projects or blog sections doesn't exist
  layouts/index.html
Labels: bug, in review

#150 Fix sorted menu
  layouts/partials/nav.html
Labels: in progress
